version: '3.3'
services:
  oasip_SVR:
    container_name: oasip_SVR
    image: oasip_back_img
    environment:
      - spring.datasource.url=jdbc:mysql://oasip_DB:3306/oasip_db
    ports:
      - '8086:8080'
    restart: always
networks:
  default:
    external:
      name: oasip_nw