version: '3.3'
services:
  oasipSVR:
    container_name: oasipSVR
    image: oasip_back_img
    environment:
      - spring.datasource.url=jdbc:mysql://oasip_DB:3307/oasip_db
    ports:
      - '8086:8080'
    restart: always
networks:
  default:
    external:
      name: oasip_nw
