version: '3.3'
services:
  oasip_DB:
    container_name: oasip_DB
    volumes:
      - /home/spadmin/OASIP/OASIP-SSA-5/Week-3/OASIP-DataBase/script/tablescript.sql:/docker-entrypoint-initdb.d/tablescript.sql
      - /home/spadmin/OASIP/OASIP-SSA-5/Week-3/OASIP-DataBase/my.cnf:/etc/mysql/my.cnf  
    environment:
      - MYSQL_USER=oasip_user
      - MYSQL_DATABASE=oasip_db
      - MYSQL_PASSWORD=kmutt@631305.78
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Bangkok
    ports:
      - '3306:3306'
    image: mysql:8
    restart: always
    command: --character-set-server=utf8mb4 --default-time-zone= +07:00
networks:
  default:
    external:
      name: oasip_nw