version: '3.3'
services:
  oasip_DB:
    container_name: oasip_DB
    volumes:
      - /home/spadmin/OASIP/OASIP-SSA-5/Week-3/OASIP-DAtaBase/script/tablescript.sql:/docker-entrypoint-initdb.d/tablescript.sql
    environment:
      - MYSQL_USER=oasip_user
      - MYSQL_DATABASE=oasip_db
      - MYSQL_PASSWORD=kmutt@631305.78
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    image: mysql:8
    restart: always
networks:
  default:
    external:
      name: oasip_nw