-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 13:22:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oasip_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oasip_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oasip_db` DEFAULT CHARACTER SET utf8 ;
USE `oasip_db` ;

-- -----------------------------------------------------
-- Table `oasip_db`.`EventCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip_db`.`EventCategory` (
  `CategoryID` INT NOT NULL,
  `CategoryName` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `duration` INT NOT NULL,
  PRIMARY KEY (`CategoryID`),
  UNIQUE INDEX `categoryName_UNIQUE` (`CategoryName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oasip_db`.`EventBooking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip_db`.`EventBooking` (
  `BookingID` INT NOT NULL,
  `BookingName` VARCHAR(50) NOT NULL,
  `BookingEmail` VARCHAR(50) NOT NULL,
  `CategoryID` INT NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `EventNote` VARCHAR(255) NULL,
  PRIMARY KEY (`BookingID`),
  INDEX `fk_EventBooking_EventCategory_idx` (`CategoryID` ASC) VISIBLE,
  CONSTRAINT `fk_EventBooking_EventCategory`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `oasip_db`.`EventCategory` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from EventBooking;
select * from EventCategory;

insert into `eventcategory` (`CategoryID`,`CategoryName`,`Description`,`Duration`) values 
(1, 'Project Management Clinic',
'ตารางนัดหมายนี้ใช้สำหรับนัดหมาย project
management clinic ในวิชา INT221 integrated
project I ให้นักศึกษาเตรียมเอกสารที่เกี่ยวข้องเพื่อแสEventBookingดง
ระหว่างขอคำปรึกษา', 30 ),
(2,'DevOps/Infra Clinic','Use this event category for DevOps/Infra clinic.',20),
(3,'Database Clinic','ตารางนัดหมายนี้ใช้สำหรับนัดหมาย database clinic ใน
วิชา INT221 integrated project I',15),
(4,'Client-side Clinic','ตารางนัดหมายนี้ใช้สำหรับนัดหมาย client-side clinic ใน
วิชา INT221 integrated project',30),
(5,'Server-side Clinic',' ',30);

insert into `EventBooking` (`BookingID`,`BookingName`,`BookingEmail`,`CategoryID`,`StartTime`,`EventNote`) values 
(1,'Somchai Jaidee (OR-7)','somchai.jai@mail.kmutt.ac.th',4,'2022-05-23 13:00',' '),
(2,'Somsri Rakdee (SJ-3)','somsri.rak@mail.kmutt.ac.th',1,'2022-04-27 09:30',' ขอปรึกษาเรื่องเพพื่อนไม่ช่วยงาน '),
(3,'สมเกียรติ ขยันเรียน กลุ่ม TT-4','somkiat.kay@kmutt.ac.th',3,'2022-05-23 16:30',' ');
