-- MySQL Script generated by MySQL Workbench
-- Sun May  1 20:32:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oasip_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oasip_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oasip_db` DEFAULT CHARACTER SET utf8 ;
USE `oasip_db` ;

-- -----------------------------------------------------
-- Table `oasip_db`.`EventCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip_db`.`EventCategory` (
  `CategoryID` INT NOT NULL,
  `CategoryName` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(550) NULL,
  `Duration` INT NOT NULL,
  PRIMARY KEY (`CategoryID`),
  UNIQUE INDEX `CategoryName_UNIQUE` (`CategoryName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oasip_db`.`EventBooking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip_db`.`EventBooking` (
  `BookingID` INT NOT NULL auto_increment ,
  `BookingName` VARCHAR(150) NOT NULL,
  `BookingEmail` VARCHAR(150) NOT NULL,
  `Category` INT NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `BookingDuration` INT NOT NULL,
  `EventNote` VARCHAR(550) NULL,
  PRIMARY KEY (`BookingID`),
  INDEX `fk_EventBooking_EventCategory_idx` (`StartTime` ASC) VISIBLE,
  CONSTRAINT `fk_EventBooking_EventCategory`
    FOREIGN KEY (`Category`)
    REFERENCES `oasip_db`.`EventCategory` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
