version: '3.3'
services:
  oasip_DB:
    container_name: oasip_DB
    volumes:
      - /home/spadmin/OASIP/OASIP-SSA-5/Week-1/OASIP-DAtaBase/script:/docker-entrypoint-initdb.d/
      - /home/spadmin/OASIP/OASIP-SSA-5/Week-1/OASIP-DAtaBase:/var/lib/mysql
    environment:
      - MYSQL_USER=oasip_user
      - MYSQL_DATABASE=oasip_db
      - MYSQL_PASSWORD=kmutt@631305.78
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    image: mysql:8
    restart: always
  oasip_SVR:
    container_name: oasip_SVR
    image: oasip_back_img
    environment:
      - spring.datasource.url=jdbc:mysql://oasip_DB:3306/oasip_db
    ports:
      - '8080:8080'
    restart: always
    links:
      - oasip_DB
