version: '3.3'
services:
  oasip_DB:
    container_name: oasip_DB
    volumes:
      - /home/spadmin/OASIP/OASIP-SSA-5/Week-1/OASIP-DAtaBase/script:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=oasip_user
      - MYSQL_DATABASE=oasip_db
      - MYSQL_PASSWORD=kmutt@631305.78
    ports:
      - '3306:3306'
    image: mysql/mysql-server
    restart: always
  oasip_SVR:
    container_name: oasip_SVR
    image: oasip_back_img
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - oasip_DB
    links:
      - oasip_DB

        
